import type { Restaurant } from './types';

export const MOCK_RESTAURANTS: Restaurant[] = [
    {
      id: '1',
      name: 'Village Pizza',
      cuisine: 'Italian',
      rating: 4.5,
      deliveryTime: '30-40 minutes',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'italian food',
    },
    {
      id: '2',
      name: 'Spice Paradise',
      cuisine: 'Indian',
      rating: 4.2,
      deliveryTime: '35-45 minutes',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'indian food',
    },
    {
      id: '3',
      name: 'The Curry Leaf',
      cuisine: 'South Indian',
      rating: 4.8,
      deliveryTime: '25-35 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'indian food',
    },
    {
      id: '4',
      name: "Mama's Pizzeria",
      cuisine: 'Pizza',
      rating: 4.6,
      deliveryTime: '30-40 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'pizza',
    },
    {
      id: '5',
      name: 'Sushi Samba',
      cuisine: 'Japanese',
      rating: 4.9,
      deliveryTime: '40-50 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'sushi',
    },
    {
      id: '6',
      name: 'Burger Barn',
      cuisine: 'American',
      rating: 4.3,
      deliveryTime: '20-30 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'burger',
    },
    {
      id: '7',
      name: 'Taco Town',
      cuisine: 'Mexican',
      rating: 4.7,
      deliveryTime: '25-35 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'taco',
    },
    {
      id: '8',
      name: 'Noodle House',
      cuisine: 'Chinese',
      rating: 4.4,
      deliveryTime: '30-40 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'noodles',
    },
  ];
