
import type { Restaurant } from './types';

// Let's assign a mock owner ID to some restaurants.
// In a real app, this would be the UID of a user with the 'owner' role.
const MOCK_OWNER_ID = 'mock-owner-uid-123';

export const MOCK_RESTAURANTS: Restaurant[] = [
    {
      id: '1',
      name: 'Village Pizza',
      cuisine: 'Italian',
      rating: 4.5,
      deliveryTime: '30-40 minutes',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'italian food',
      ownerId: MOCK_OWNER_ID,
      status: 'approved',
      deliveryCharge: 2.50,
      isOpen: true,
      paymentMethods: {
        cash: true,
        upi: true,
        upiId: 'village.pizza@upi',
        upiQrCodeUrl: 'https://placehold.co/200x200.png',
      },
      reviewCount: 150,
    },
    {
      id: '2',
      name: 'Spice Paradise',
      cuisine: 'Indian',
      rating: 4.2,
      deliveryTime: '35-45 minutes',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'indian food',
      status: 'approved',
      deliveryCharge: 1.99,
      isOpen: true,
       paymentMethods: {
        cash: true,
        upi: false,
      },
      reviewCount: 230,
    },
    {
      id: '3',
      name: 'The Curry Leaf',
      cuisine: 'South Indian',
      rating: 4.8,
      deliveryTime: '25-35 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'indian food',
      status: 'approved',
      deliveryCharge: 0,
      isOpen: true,
       paymentMethods: {
        cash: true,
        upi: true,
        upiId: 'curry.leaf@upi',
        upiQrCodeUrl: 'https://placehold.co/200x200.png',
      },
      reviewCount: 310,
    },
    {
      id: '4',
      name: "Mama's Pizzeria",
      cuisine: 'Pizza',
      rating: 4.6,
      deliveryTime: '30-40 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'pizza',
      status: 'approved',
      deliveryCharge: 3.00,
      isOpen: false,
       paymentMethods: {
        cash: true,
        upi: false,
      },
       reviewCount: 180,
    },
    {
      id: '5',
      name: 'Sushi Samba',
      cuisine: 'Japanese',
      rating: 4.9,
      deliveryTime: '40-50 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'sushi',
      status: 'approved',
      deliveryCharge: 5.00,
      isOpen: true,
       paymentMethods: {
        cash: true,
        upi: false,
      },
      reviewCount: 450,
    },
    {
      id: '6',
      name: 'Burger Barn',
      cuisine: 'American',
      rating: 4.3,
      deliveryTime: '20-30 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'burger',
      ownerId: 'mock-owner-uid-456',
      status: 'approved',
      deliveryCharge: 0,
      isOpen: true,
       paymentMethods: {
        cash: true,
        upi: false,
      },
       reviewCount: 95,
    },
    {
      id: '7',
      name: 'Taco Town',
      cuisine: 'Mexican',
      rating: 4.7,
      deliveryTime: '25-35 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'taco',
      status: 'approved',
      deliveryCharge: 1.50,
      isOpen: true,
       paymentMethods: {
        cash: true,
        upi: false,
      },
       reviewCount: 120,
    },
    {
      id: '8',
      name: 'Noodle House',
      cuisine: 'Chinese',
      rating: 4.4,
      deliveryTime: '30-40 min',
      image: 'https://placehold.co/600x400',
      dataAiHint: 'noodles',
      status: 'approved',
      deliveryCharge: 2.00,
      isOpen: true,
       paymentMethods: {
        cash: true,
        upi: false,
      },
       reviewCount: 160,
    },
  ];
